name: Release Windows Binary

on:
  push:
    tags:
      - windows-v*

jobs:
  release:
    name: Release Windows Binary
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          goos: windows
          goarch: ${{ matrix.goarch }}
          binary_name: "deeplx"
          ldflags: -H=windowsgui
          executable_compression: upx --ultra-brute --no-lzma
          extra_files: url.txt
          overwrite: true